# Generated by Django 5.0.14 on 2025-06-12 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('numero_telefonico', models.CharField(max_length=15)),
                ('atendio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InicioLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('clave', models.CharField(max_length=50)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paqueteria.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('num_telefonico', models.CharField(max_length=15)),
                ('contenido', models.TextField(max_length=2000)),
                ('destinatario', models.CharField(max_length=200)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('direccion_destino', models.CharField(max_length=250)),
                ('referencias_destino', models.TextField(max_length=3500)),
                ('medida_ancho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medida_alto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medida_largo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paqueteria', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paqueteria.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_entrega', models.DateField()),
                ('hora_entrega', models.TimeField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paqueteria.sucursal')),
            ],
        ),
    ]
